using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.ComponentModel;
namespace MMManager
{
    /// <summary>
    /// Class to manage Instances of MC in time
    /// Including Core Dependencies.
    /// </summary>
    [Serializable]
    class MMMInstance
    {

        /// <summary>
        /// Name of this Instance - Can be autogenerated or typed but
        /// should be mutually exclusive such that there are not duplicates of contained
        /// classes..
        /// </summary>
        public String InstanceName {get; set; }
        /// <summary>
        /// True if this is the active instance
        /// </summary>
        public Boolean ActiveInstance { get; set; }
        /// <summary>
        /// Version Information
        /// </summary>
        public String MineCraftVersion {get; set; }
        /// <summary>
        /// Version Information
        /// </summary>
        public String ForgeVersion {get; set;}

    }
}
